name: Tests

on:
  push:
    branches: [ main, develop, CesarMoreno ]
  pull_request:
    branches: [ main, develop, CesarMoreno ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      run: mvn -B -V clean verify

    - name: Upload JAR
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: apiProductos-jar
        path: target/*.jar
